### ISSUE TITLE
Comparison with Linkerd2 is wrong

### ISSUE THREAD

**Issue by sateffen** [envoyproxy/envoyproxy.github.io#126]
The [comparison with linkerd](https://www.envoyproxy.io/docs/envoy/latest/intro/comparison#id7) is wrong, as of [linkerd2](https://linkerd.io/2/overview/).

Linkerd itself is a complete service-mesh, and not only a proxy, and the proxy itself is written in Rust and based on Tokio, no JVM-based language. Maybe that part should get revisited?

**Comment by mattklein123** [comment]
My feeling is we should just remove the comparison page at this point. It will inevitable always be out of date and at this point Envoy is well known enough that I'm not sure it's necessary.

@envoyproxy/maintainers thoughts here?

**Comment by alyssawilk** [comment]
Voting with my PR.  We can land or revert :-)
