### ISSUE TITLE
Missing explanation or incorrect logic in stale-requests.svg ?

### ISSUE THREAD

**Issue by sanjaypujare** [envoyproxy/envoyproxy.github.io#128]
Looking at the sequence diagram 
https://github.com/envoyproxy/envoyproxy.github.io/blob/master/docs/envoy/latest/_images/stale-requests.svg included in the page https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#resource-updates I see an inconsistency.

The first request (top green arrow) is considered stale for (V=X, N=A, R={foo})  for whatever reason. However the second request (second green arrow) is not considered stale with (V=X, N=A) just because R={foo,bar} i.e. a resource name `bar` was added. However the 3rd request (3rd green arrow) is considered stale with (V=X, N=A) even if a new resource name `baz` was added. Why is that? Why does Envoy need to upgrade (V=Y, N=B) for the request to be considered not-stale even if a new resource `baz` was added?

**Comment by mattklein123** [comment]
The documentation source is here: https://github.com/envoyproxy/envoy/blob/master/api/xds_protocol.rst.

Please open an issue/PR against the main repo.
