### ISSUE TITLE
Missing part in edge proxy configuration example?

### ISSUE THREAD

**Issue by lewislbr** [envoyproxy/envoyproxy.github.io#168]
Hello,

I've been following the [example about configuring Envoy as an edge proxy](https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge#best-practices-edge), and the only way to make it work was adding:

```yaml
http_filters:
  - name: envoy.filters.http.router
```

like it is in the [getting started page](https://www.envoyproxy.io/docs/envoy/latest/start/start).

Should it be added, or am I missing something?

**Comment by mattklein123** [comment]
If this is still an issue please open an issue over in https://github.com/envoyproxy/envoy
