### ISSUE TITLE
Update latest versions

### ISSUE THREAD

**Issue by moderation** [envoyproxy/envoyproxy.github.io#176]
Website not currently showing latest versions. https://github.com/envoyproxy/envoyproxy.github.io/blob/master/_config.yml needs to be updated with
- 1.16.1
- 1.16.2
- 1.15.1
- 1.15.3
- 1.14.6
- 1.13.7

https://github.com/envoyproxy/envoy/releases

/cc @phlax

**Comment by moderation** [comment]
Latest 1.17.1 release hasn't made it over here and therefore the website - https://github.com/envoyproxy/envoyproxy.github.io/blob/main/_config.yml#L23-L26

**Comment by mattklein123** [comment]
OK do you want to just do a PR? Otherwise I can do it.

**Comment by moderation** [comment]
I'll do it. Need to remind release managers that this is part of a release. Pretty sure it is documented

**Comment by moderation** [comment]
https://github.com/envoyproxy/envoyproxy.github.io/pull/182
