### ISSUE TITLE
cannot clone this repository

### ISSUE THREAD

**Issue by zg** [envoyproxy/envoyproxy.github.io#187]
When attempting to clone this repository, I get the following error:
```
$ git clone https://github.com/envoyproxy/envoyproxy.github.io
Cloning into 'envoyproxy.github.io'...
remote: Enumerating objects: 9652779, done.
remote: Counting objects: 100% (212143/212143), done.
remote: Compressing objects: 100% (39902/39902), done.
Receiving objects: 100% (9652779/9652779), 2.90 GiB | 14.52 MiB/s, done.
remote: Total 9652779 (delta 110329), reused 211797 (delta 109990), pack-reused 9440636
fatal: fetch-pack: invalid index-pack output
```
Note that it took nearly 10 minutes for the entire repository to download before failing on this error.

**Comment by phlax** [comment]
the repo is huge - not sure how we can deal with that

i think you can probably workaround with the advice here https://stackoverflow.com/questions/21277806/fatal-early-eof-fatal-index-pack-failed

**Comment by zg** [comment]
Why is it so huge? Does it really have to be 2.9 GiB? 😅

**Comment by phlax** [comment]
> Does it really have to be 2.9 GiB

perhaps not in a parallel reality

> Why is it so huge?

it does a merge on every commit to the envoy repo - i forget the exact details but iirc its something to do with binary updates

it would be great if we could resolve - there are a load of changes/updates i would like to make but reluctant to check out the repo

**Comment by phlax** [comment]
checking here https://github.com/envoyproxy/envoyproxy.github.io/commit/fb00e73f9a112e4a25d36c7f457a8c613bcf1fc5  it seems to be not binary updates but just a huge volume of text changes in every commit

i think one possible resolution is not committing the html to the repo and having netlify build the docs from rst

the changes would still be quite bit - but at least a lot smaller than now

its not a trivial change tho

**Comment by phlax** [comment]
tbh - thinking about it im wondering why all of the docs need to be committed here at all

netlify could just pull from latest/specific commits on main repo and build the docs from there - altho we would need to either commit the generated rst files in envoy or have netlify do the rst generation somehow

**Comment by phlax** [comment]
@zg i have created #188 to address the underlying cause of the problem

**Comment by zg** [comment]
Thanks! Feel free to close this in favor of that issue, since I was able to clone after giving the command a second try.
