### ISSUE TITLE
Getting an error: www.envoyproxy.io redirected too many times

### ISSUE THREAD

**Issue by chalin** [envoyproxy/envoyproxy.github.io#193]
Getting the error "www.envoyproxy.io redirected you too many times" intermittently, though more often than not today (2021-08-21).

/cc @nate-double-u

**Comment by mattklein123** [comment]
I will follow up with Netlify, it seems the fix we did did not work.

**Comment by mattklein123** [comment]
Netlify says they changed something. Please ping this ticket in case anyone sees this again, thanks.

**Comment by chalin** [comment]
> Netlify says they changed something. Please ping this ticket in case anyone sees this again, thanks.

Tested again today (2021/09/07), and the looped redirecting is still happening:
> <img src="https://user-images.githubusercontent.com/4140793/132355385-7bf5f5f9-1f64-407a-a492-a14150d6a343.png" width=500>

/cc @caniszczyk

**Comment by mattklein123** [comment]
Thanks. I will ping the netlify ticket.

**Comment by phlax** [comment]
see also https://github.com/envoyproxy/envoy/pull/17296#issuecomment-914260480

**Comment by phlax** [comment]
great news! this seems to be fixed now, at least in terms of the default config and http -> https sni

**Comment by phlax** [comment]
closing this as i believe it has now been resolved
