### ISSUE TITLE
URL listed on top level github is incorrect / broken

### ISSUE THREAD

**Issue by packeteer** [envoyproxy/envoyproxy.github.io#5]
![screen shot 2017-09-27 at 14 08 34](https://user-images.githubusercontent.com/5533448/30895442-94449be4-a38d-11e7-969c-3beb24305a26.png)

http://envoyproxy.io/ doesn't go anywhere, add https and you get a cert error

**Comment by caniszczyk** [comment]
This should be fixed soon, give us a couple days

**Comment by mattklein123** [comment]
I just switched this temporarily to a working one. We will switch it back when the new domain is fully working.

**Comment by mattklein123** [comment]
This is fixed
