### ISSUE TITLE
Please update the Google logo

### ISSUE THREAD

**Issue by craigbox** [envoyproxy/envoyproxy.github.io#8]
You're using the old Google logo at https://envoyproxy.github.io/img/logos/google.svg

Could you please update it to the new logotype?

You can base it on https://chromium.googlesource.com/chromium/src/+/master/ui/webui/resources/images/google_logo.svg.

**Comment by richarddli** [comment]
Yes, will do.

**Comment by mattklein123** [comment]
Fixed
