### ISSUE TITLE
The website's SSL certificate out of date

### ISSUE THREAD

**Issue by rootsongjc** [envoyproxy/envoyproxy.github.io#85]
The envoy proxy website https://envoyproxy.io will load the invalid SSL certificate sometimes. It really disturbed me to surf the envoy's website. How can we deal with this?

![image](https://user-images.githubusercontent.com/3328185/49788872-774f2580-fd65-11e8-8225-b9ce7063ebe8.png)
![image](https://user-images.githubusercontent.com/3328185/49788915-9483f400-fd65-11e8-9164-7f383f88a826.png)

**Comment by lucperkins** [comment]
@ rootsongjc Is this still an issue? I'm not able to recreate the problem.

**Comment by rootsongjc** [comment]
@lucperkins It disappeared, so I close this issue.
