### ISSUE TITLE
Website not updating

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoyproxy.github.io#90]
@lucperkins @richarddli can one of you potentially take a look at what is going on? The commits are coming into this repo, so it seems like some type of netlify issue.

**Comment by caniszczyk** [comment]
@lucperkins invited

**Comment by lucperkins** [comment]
@mattklein123 Updating the Ruby version seems to have done the trick, at least for now (see #91 and the [build output](https://app.netlify.com/sites/teacher-glances-63085/deploys/5c3bda47013f7b0008bb9068)). I'll be keeping an eye on this in the coming days. If things regress, feel free to re-open the issue. Closing for now.
